/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CompteRouteImport } from './routes/compte'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVentesRouteImport } from './routes/_authenticated/ventes'
import { Route as AuthenticatedUtilisateursRouteImport } from './routes/_authenticated/utilisateurs'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedReservationsRouteImport } from './routes/_authenticated/reservations'
import { Route as AuthenticatedRapportsRouteImport } from './routes/_authenticated/rapports'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedHistoriqueRouteImport } from './routes/_authenticated/historique'
import { Route as AuthenticatedGestionCatalogueRouteImport } from './routes/_authenticated/gestion-catalogue'
import { Route as AuthenticatedDepensesRouteImport } from './routes/_authenticated/depenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommandesLivraisonRouteImport } from './routes/_authenticated/commandes-livraison'
import { Route as AuthenticatedCatalogueRouteImport } from './routes/_authenticated/catalogue'
import { Route as AuthenticatedAdminConfigurationRouteImport } from './routes/_authenticated/admin-configuration'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRoute = CompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVentesRoute = AuthenticatedVentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUtilisateursRoute =
  AuthenticatedUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReservationsRoute =
  AuthenticatedReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRapportsRoute = AuthenticatedRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoriqueRoute = AuthenticatedHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGestionCatalogueRoute =
  AuthenticatedGestionCatalogueRouteImport.update({
    id: '/gestion-catalogue',
    path: '/gestion-catalogue',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDepensesRoute = AuthenticatedDepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommandesLivraisonRoute =
  AuthenticatedCommandesLivraisonRouteImport.update({
    id: '/commandes-livraison',
    path: '/commandes-livraison',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogueRoute = AuthenticatedCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminConfigurationRoute =
  AuthenticatedAdminConfigurationRouteImport.update({
    id: '/admin-configuration',
    path: '/admin-configuration',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compte': typeof CompteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/admin-configuration': typeof AuthenticatedAdminConfigurationRoute
  '/catalogue': typeof AuthenticatedCatalogueRoute
  '/commandes-livraison': typeof AuthenticatedCommandesLivraisonRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/depenses': typeof AuthenticatedDepensesRoute
  '/gestion-catalogue': typeof AuthenticatedGestionCatalogueRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/rapports': typeof AuthenticatedRapportsRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/utilisateurs': typeof AuthenticatedUtilisateursRoute
  '/ventes': typeof AuthenticatedVentesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compte': typeof CompteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/admin-configuration': typeof AuthenticatedAdminConfigurationRoute
  '/catalogue': typeof AuthenticatedCatalogueRoute
  '/commandes-livraison': typeof AuthenticatedCommandesLivraisonRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/depenses': typeof AuthenticatedDepensesRoute
  '/gestion-catalogue': typeof AuthenticatedGestionCatalogueRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/rapports': typeof AuthenticatedRapportsRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/utilisateurs': typeof AuthenticatedUtilisateursRoute
  '/ventes': typeof AuthenticatedVentesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/compte': typeof CompteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/_authenticated/admin-configuration': typeof AuthenticatedAdminConfigurationRoute
  '/_authenticated/catalogue': typeof AuthenticatedCatalogueRoute
  '/_authenticated/commandes-livraison': typeof AuthenticatedCommandesLivraisonRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/depenses': typeof AuthenticatedDepensesRoute
  '/_authenticated/gestion-catalogue': typeof AuthenticatedGestionCatalogueRoute
  '/_authenticated/historique': typeof AuthenticatedHistoriqueRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/rapports': typeof AuthenticatedRapportsRoute
  '/_authenticated/reservations': typeof AuthenticatedReservationsRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/utilisateurs': typeof AuthenticatedUtilisateursRoute
  '/_authenticated/ventes': typeof AuthenticatedVentesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compte'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/shop'
    | '/admin-configuration'
    | '/catalogue'
    | '/commandes-livraison'
    | '/dashboard'
    | '/depenses'
    | '/gestion-catalogue'
    | '/historique'
    | '/profil'
    | '/rapports'
    | '/reservations'
    | '/stock'
    | '/utilisateurs'
    | '/ventes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compte'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/shop'
    | '/admin-configuration'
    | '/catalogue'
    | '/commandes-livraison'
    | '/dashboard'
    | '/depenses'
    | '/gestion-catalogue'
    | '/historique'
    | '/profil'
    | '/rapports'
    | '/reservations'
    | '/stock'
    | '/utilisateurs'
    | '/ventes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/compte'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/shop'
    | '/_authenticated/admin-configuration'
    | '/_authenticated/catalogue'
    | '/_authenticated/commandes-livraison'
    | '/_authenticated/dashboard'
    | '/_authenticated/depenses'
    | '/_authenticated/gestion-catalogue'
    | '/_authenticated/historique'
    | '/_authenticated/profil'
    | '/_authenticated/rapports'
    | '/_authenticated/reservations'
    | '/_authenticated/stock'
    | '/_authenticated/utilisateurs'
    | '/_authenticated/ventes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CompteRoute: typeof CompteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte': {
      id: '/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ventes': {
      id: '/_authenticated/ventes'
      path: '/ventes'
      fullPath: '/ventes'
      preLoaderRoute: typeof AuthenticatedVentesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/utilisateurs': {
      id: '/_authenticated/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof AuthenticatedUtilisateursRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reservations': {
      id: '/_authenticated/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AuthenticatedReservationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rapports': {
      id: '/_authenticated/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof AuthenticatedRapportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historique': {
      id: '/_authenticated/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AuthenticatedHistoriqueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestion-catalogue': {
      id: '/_authenticated/gestion-catalogue'
      path: '/gestion-catalogue'
      fullPath: '/gestion-catalogue'
      preLoaderRoute: typeof AuthenticatedGestionCatalogueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/depenses': {
      id: '/_authenticated/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof AuthenticatedDepensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/commandes-livraison': {
      id: '/_authenticated/commandes-livraison'
      path: '/commandes-livraison'
      fullPath: '/commandes-livraison'
      preLoaderRoute: typeof AuthenticatedCommandesLivraisonRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalogue': {
      id: '/_authenticated/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof AuthenticatedCatalogueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin-configuration': {
      id: '/_authenticated/admin-configuration'
      path: '/admin-configuration'
      fullPath: '/admin-configuration'
      preLoaderRoute: typeof AuthenticatedAdminConfigurationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminConfigurationRoute: typeof AuthenticatedAdminConfigurationRoute
  AuthenticatedCatalogueRoute: typeof AuthenticatedCatalogueRoute
  AuthenticatedCommandesLivraisonRoute: typeof AuthenticatedCommandesLivraisonRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepensesRoute: typeof AuthenticatedDepensesRoute
  AuthenticatedGestionCatalogueRoute: typeof AuthenticatedGestionCatalogueRoute
  AuthenticatedHistoriqueRoute: typeof AuthenticatedHistoriqueRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedRapportsRoute: typeof AuthenticatedRapportsRoute
  AuthenticatedReservationsRoute: typeof AuthenticatedReservationsRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedUtilisateursRoute: typeof AuthenticatedUtilisateursRoute
  AuthenticatedVentesRoute: typeof AuthenticatedVentesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminConfigurationRoute: AuthenticatedAdminConfigurationRoute,
  AuthenticatedCatalogueRoute: AuthenticatedCatalogueRoute,
  AuthenticatedCommandesLivraisonRoute: AuthenticatedCommandesLivraisonRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepensesRoute: AuthenticatedDepensesRoute,
  AuthenticatedGestionCatalogueRoute: AuthenticatedGestionCatalogueRoute,
  AuthenticatedHistoriqueRoute: AuthenticatedHistoriqueRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedRapportsRoute: AuthenticatedRapportsRoute,
  AuthenticatedReservationsRoute: AuthenticatedReservationsRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedUtilisateursRoute: AuthenticatedUtilisateursRoute,
  AuthenticatedVentesRoute: AuthenticatedVentesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CompteRoute: CompteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
